#!/bin/bash

##  `getLinkRef <file>` extracts a `/`-separated list consisting of the
##  content of each "second consecutive square bracket": for instance
##  ```
##  printf 'text [1][2], more text, [3][4]\n[5][6]' | getLinkRef -
##  > 2/4/6/
##  ```
getLinkRef () {
  grep "\]\[" "${1}" |
    sed 's=[^[]*\[[^]]*\]\[\([^]]*\)\][^[]*=\1/=g' |
    tr --squeeze-repeats "/" "\n"
}

outerret 'printf "text [1][2], more text, [3][4]\n[5][6]" | getLinkRef -' $'2\n4\n6\n' '' 0

##  `mkLink <file>` search for `<file>.lean` starting from the git root directory
##  returns the url for opening `<file>.lean` with the lean-web-editor.
##  it also assigns as "hover name" to the link the name of the file with
##  underscores (`_`) replaced by spaces (` `).
mkLink () {
  local pth url
  pth="$(git rev-parse --show-toplevel)"
  url='https://leanprover-community.github.io/lean-web-editor/#url=https://raw.githubusercontent.com/adomani/Atelier_Lean_2023/master'
  find "${pth}" -name "${1}.lean" | sed "s|${pth}|[${1}]: ${url}|; s|$| \"${1//_/ }\"|"
}

##  `allLinks <file>` extracts the md-encoded url-refs from `<file>` and
##  produces the actual url links.
allLinks () {
  (
    cd "$(git rev-parse --show-toplevel)"
    echo '<!--  Autogenerated links  -->'
    for fil in $(getLinkRef "${1}"); do
      mkLink ${fil}
    done
  )
}

autolinks () {
  sed '/<!--  Autogenerated links  -->/Q' "${1}" |
    tee >(allLinks -)
}
